# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  # - name: News
  #   url: post
  #   weight: 20
  - name: 成员
    url: people
    weight: 20
  - name: 本组
    url: group
    weight: 30
  - name: 书籍
    url: textbook
    weight: 40
  - name: 论文
    url: publication
    weight: 50
  - name: 数据集
    url: dataset
    weight: 60
  - name: 新芽
    url: sprouts
    weight: 70
  - name: 教学
    url: teaching
    weight: 80
  - name: 获奖
    url: award
    weight: 90
  - name: 开源
    url: open-source
    weight: 100
  - name: 博客
    url: blog
    weight: 110
  - name: 漫画
    url: comics
    weight: 120    
  - name: 照片
    url: photo
    weight: 130    
  - name: 视频
    url: event
    weight: 140
  - name: 设备
    url: device
    weight: 150
  - name: 联系
    url: contact
    weight: 160
  - name: 提问
    url: https://github.com/GrokCV/website/discussions
    weight: 170
  # - name: Contact
  #   url: contact
  #   weight: 60
